export const categories = [
    "All",
    "Platform Guides",
    "Strategy & Insights",
    "Creator Growth",
    "Agency Workflows",
    "News & Updates",
];

export const blogPosts = [
    {
        id: 1,
        title: "The Ultimate Guide to TikTok Algorithm in 2026",
        excerpt: "Unlock the secrets of the TikTok For You Page with our comprehensive guide on ranking factors, hashtags, and viral sounds.",
        category: "Platform Guides",
        author: "Sarah Jenkins",
        date: "Oct 12, 2025",
        readTime: "8 min read",
        image: "/images/blog/tiktok-algo.jpg", // Placeholder path
        slug: "tiktok-algorithm-guide-2026",
        featured: true,
    },
    {
        id: 2,
        title: "How to Scale Your Social Media Agency to 50 Clients",
        excerpt: "Learn the operational frameworks, hiring strategies, and pricing models used by top agencies to grow without seeking.",
        category: "Agency Workflows",
        author: "Michael Ross",
        date: "Oct 10, 2025",
        readTime: "12 min read",
        image: "/images/blog/agency-scale.jpg",
        slug: "scale-social-media-agency",
        featured: false,
    },
    {
        id: 3,
        title: "Instagram SEO: Ranking Your Profile and Posts",
        excerpt: "Instagram is a search engine. Here is how to optimize your bio, captions, and alt text to get discovered by new followers.",
        category: "Strategy & Insights",
        author: "Jessica Li",
        date: "Oct 05, 2025",
        readTime: "6 min read",
        image: "/images/blog/ig-seo.jpg",
        slug: "instagram-seo-ranking",
        featured: false,
    },
    {
        id: 4,
        title: "SocialHub 2.0: Introducing AI Video Scripts",
        excerpt: "Our biggest update yet. Generate video scripts for Reels and TikToks instantly from a simple text prompt.",
        category: "News & Updates",
        author: "Team SocialHub",
        date: "Sep 28, 2025",
        readTime: "4 min read",
        image: "/images/blog/update-2-0.jpg",
        slug: "socialhub-2-0-ai-video",
        featured: false,
    },
    {
        id: 5,
        title: "Creator Burnout: Signs and Prevention Strategies",
        excerpt: "Content creation is a marathon, not a sprint. Learn how to protect your mental health while maintaining consistency.",
        category: "Creator Growth",
        author: "Dr. Emily Chen",
        date: "Sep 15, 2025",
        readTime: "9 min read",
        image: "/images/blog/burnout.jpg",
        slug: "creator-burnout-prevention",
        featured: false,
    },
];
